### ISSUE TITLE
Contribute nollup code into rollup

### ISSUE THREAD

**Issue by stalniy** [PepsRyuu/nollup#113]
Now, rollup allows to disable tree shaking and probably other optimizations, so maybe it's time to move own work into a plugin or contribute back into rollup?

**Comment by PepsRyuu** [comment]
Tree-shaking is only a tiny part of the problem. 

There's several other issues that are completely misaligned to what a development bundle requires (no scope hoisting, module wrapping, require/module and other Webpack semantics, lots of caching, in-memory asset generation, code deltas for HMR, dev plugin hooks for HMR optimisation, skipping all prod related code and prod hooks, dev server and middleware). It's basically impossible with just a plugin, and there would be a lot of significant changes required to the Rollup codebase to even make it somewhat feasible. It's easier to just create a fresh project with a fresh objective.

Outside of the technical side of things, a separate project gives me more breathing room to experiment and to make decisions that I feel make the most sense for a developer experience. As recent trends also show, other developers are doing something similar, creating new innovative developer experiences but using Rollup as a bundler for production builds. This is something I feel makes more sense for Rollup to focus on, rather than trying to tack on a developer experience that likely won't make everyone happy. As a separate project, developers can pick the experience that makes sense for them.

Hope that helps answer your question!

**Comment by stalniy** [comment]
But as far as I understand you need to maintain the compatibility between plugins and rollup API. And sometimes this compatibility may be broken. 

Also, for me as an app developer is important to understand that the app in dev mode behaves in exactly the same way as in prod mode. Otherwise, I'll find issues on later stage and the team will pay higher price.

We also now have an option to `preserveModules`. Maybe it'd be good to discuss required functionality and possible changes with @shellscape . If webpack supports this, why can't rollup?

**Comment by PepsRyuu** [comment]
That is a downside yes. Vite, Snowpack, and others all share the same downsides in their implementations in trying to reuse Rollup plugin hooks. I think Rollup exposing the Plugin API as a library were each hook can be called separately would be a great, lets me focus on the code generation and developer experience side of things, and the other projects would likely appreciate it as well. Not sure what that library would look like though.

There's always a possibility of differences between dev and prod, regardless of what tool you're using. Even if Rollup provided a dev bundle, there's always a possibility it could be functionally different than prod. Plugins can do the same thing like Babel injection dev runtimes, even the code in the app can behave differently depending on environment variables. That possibility can never be eliminated, but at the moment, things should be very much aligned for the vast majority of cases. It's very unlikely though that the plugin API specifically will result in significant differences.

```preserveModules``` wouldn't suffice either, because it keeps files separate and maintains the folder structure of the source input, while breaking a lot of configurations and introducing a lot of complexity for developers that will hurt the overall dev experience.

I don't have the capacity or desire to look into such a massive undertaking, nor can I envision what an API to enable a developer bundler would look like that doesn't involve a huge rewrite. And again, considering that we have many new developer tools that use Rollup as a prod bundler, I don't think it makes sense for Rollup to focus on this at all as their primary advantage is being incredibly awesome at prod bundles compared to all other tools. Trying to be an all-rounder and changing gears to provide a fully fledged dev experience seems like it would be a mistake. I personally prefer lightweight specialised tools that only focus on a single thing, rather than entire frameworks.

**Comment by stalniy** [comment]
I see. It makes sense. Thanks for detailed explanation
