### ISSUE TITLE
Nollup doesn't provide an option to select the host

### ISSUE THREAD

**Issue by itssumitrai** [PepsRyuu/nollup#120]
I was trying to use Nollup in my project, due to CORS restrictions, I wanted to get a particular host  and not the default `localhost`, but seems like there is no option in Nollup cli to set the hostname to open which I feel is a gap. All other dev server libs like `webpack-dev-server`, `snowpack`, etc provide this option.

ref: [https://github.com/PepsRyuu/nollup/blob/master/docs/cli.md](https://github.com/PepsRyuu/nollup/blob/master/docs/cli.md)

Remediation:

Nollup cli should add an option: `host` or `hostname` having default value of `localhost`, but which could be changed to something else like `localhost.xyz.com`

**Comment by PepsRyuu** [comment]
Can you elaborate? What's the architecture of the project and the name of the option?

**Comment by itssumitrai** [comment]
@PepsRyuu Yeah, what I mean is, there is no way to configure the host currently, its always `localhost`. There should be an option to change the host to something like `localhost.xyz.com` for example. There needs to be an option in the cli for this purpose

**Comment by PepsRyuu** [comment]
I'm not following at all. You want to be able to type in ```http://localhost.xyz.com``` into the browser and have it redirect to your locally running development server?

**Comment by hanswilw** [comment]
I think he might want to do something like I do separately now, GETing the assets from another host / port without cors issues. Like I host a django project on port 8000, and host bundle JS on 9001, then `<script src="localhost:9001/main.js" />` gives access control error.
Would love for this to be configurable in nollup in some way as well.

One workaround is to use cors() for the dev server and run with node:
```
let path = require('path');
let cors = require('cors');
let NollupDevServer = require('nollup/lib/dev-server');

NollupDevServer({
    config: path.normalize(process.cwd() + '/nollup.config.js'),
    before: (app) => {
        app.use(cors());
    },
});
```

**Comment by itssumitrai** [comment]
I just want an option to change the default `host` value while running Nollup dev server. Just like all the other dev servers have this option

```
`host: 'localhost',`
```

https://github.com/thgh/rollup-plugin-serve#options
https://webpack.js.org/configuration/dev-server/#devserverhost

This option is so that user can open their own host, instead of always opening `localhost` for whatever reason. My reason is for CORS. Like I said earlier, its very basic for this option to exist in any dev server.

**Comment by PepsRyuu** [comment]
Can you provide a reproducible example of this use case? I'm not very familiar with this option, and I can't seem to trigger CORS error when trying to use script tags accessing localhost. Need to make sure I understand what triggers this issue so I can make sure the changes I push work. :)

**Comment by morbidick** [comment]
I encountered the CORS issue when  served my html from eg. `html.localhost` (because its provided from another service) and tried referencing js served by nollup from `localhost:1234`.

I think the `host` option in other dev-servers is more about port binding and security from the outside. To fix the CORS issue setting the header `Access-Control-Allow-Origin` to `*` would suffice. I am not sure if nollup should have a simple option to enable it or if it should be done (as mentioned in other threads) via the `before`hook. 

What do you think @PepsRyuu . If you are interested i would be glad to add a PR since I kind of need it for another project (i would be fine with the hook too).

**Comment by morbidick** [comment]
I created a small repro https://github.com/PepsRyuu/nollup/pull/131 just start rollup `npm start`, the webserver `npm run server` and open `http://localhost:9000`. You will see an CORS error in the console.

**Comment by PepsRyuu** [comment]
Thanks for the repro! I'm very hesitant to add a ```cors``` option, just because it seems like it would open up potential security vulnerabilities. A malicious website could listen to ```localhost``` to steal potentially confidential information, and usually proxying is a better solution to CORS which is vulnerable to CSRF attacks.

I think the ```before``` solution is the way to go because it gives the developer full control over how the dev server is exposed and can add restrictions that fits for them.

**Comment by hanswilw** [comment]
Could provide a headers option maybe, that is not defaulted?

**Comment by PepsRyuu** [comment]
I'd be okay with that as well as a middle-ground solution if anyone wants to contribute it. :)
