### ISSUE TITLE
Discussion: sourcemaps for vanilla JSC

### ISSUE THREAD

**Issue by derolf** [PepsRyuu/nollup#147]
https://github.com/PepsRyuu/nollup/blob/895a0213ff36aedd3f081c13ad8ba6fa6d9ad8f4/lib/impl/CodeGenerator.js#L70

Nollup evaluates code using `eval`. That makes debugging harder. It would be nice to a) understand the rational of why eval is being used and b) have an option to turn off eval.

**Comment by PepsRyuu** [comment]
```eval``` is used to allow source maps to be built independently for modules for easier debugging, for significantly improved performance, and for enabling Hot Module Replacement. 

Not using ```eval``` would mean that a global source map would have to be used, which will drastically increase build times due to source map collapsing, and HMR would be impossible.

**Comment by derolf** [comment]
Ok, got it. JSC hasn't builtin support for source-maps, so this is everything gets screwed up...

**Comment by derolf** [comment]
I am still trying to get sourcemaps to work on a vanilla JSC. A vanilla JSC basically hasn’t got its own network stack, but you can attach via Safari to it. Questions

1: are nollup sourcemaps usually working in Safari?

2: how are source files served by nollup? Would it be possible to make them to include the entire url including host and port etc?

**Comment by PepsRyuu** [comment]
I haven't tested Safari because I don't have any access to a Mac, so I can't say what the behaviours are or what's possible. :(

**Comment by PepsRyuu** [comment]
Closing in favour of https://github.com/PepsRyuu/nollup/issues/149
