### ISSUE TITLE
Using SystemJS instead of custom module format

### ISSUE THREAD

**Issue by Amareis** [PepsRyuu/nollup#157]
If compile every module into a independent SystemJS module, every edgy case (like live binding & circular imports) will be solved. And if use custom systemjs extra to "bake in" module id (like a named modules extra), bundling will be as easy as string concatenation. Also, it open a opportunity to use import.meta.hot spec - https://github.com/snowpackjs/esm-hmr - instead of custom format.

**Comment by charlag** [comment]
SystemJS doesn't support hot module reloading I think?
There was some effort but it died out

**Comment by Amareis** [comment]
It shouldn't support it, since hot realoading is implemented "inside" of modules itself.

**Comment by PepsRyuu** [comment]
Apologies for not getting back to this, life got in the way unfortunately! Here's the reasons why SystemJS isn't preferable:

* Doesn't support ```module```  or ```require```, which is essential for Webpack-orientated HMR frameworks to work. While this has thankfully been changing from library source code to plugins, it would be a huge backwards incompatibility to introduce at this stage. Would rather wait until there's some more uniformity and community support before diverging from commonly accepted practice to make adoption of Nollup easier. 

* The loader doesn't actually implement live-bindings. ESM code will still need to be walked over for bindings and their modifications and switched to function calls. A complex compilation step is still required (still WIP, need to get back to it). Also it isn't entirely desirable to always compile live-bindings due to serious performance implications.

* As mentioned above, as far as I understand, SystemJS doesn't support HMR officially. Nollup actually has a fairly accurate HMR solution compared to other bundlers. It addresses various edge cases that have been thoroughly tested. Switching to a third-party vendor would weaken the ability to address those type of use cases.

**Comment by Amareis** [comment]
>The loader doesn't actually implement live-bindings. ESM code will still need to be walked over for bindings and their modifications and switched to function calls. A complex compilation step is still required (still WIP, need to get back to it). Also it isn't entirely desirable to always compile live-bindings due to serious performance implications.

SystemJS implements live bindings, actually. Its purpose is reflect full ESM semantic (including bindings).

>Would rather wait until there's some more uniformity and community support before diverging from commonly accepted practice to make adoption of Nollup easier.

Yep, and I really want to esm-hmr being this practice :) For any rollup-oriented tools it's natural way to do it, via ESM syntax.

>SystemJS doesn't support HMR officially

Loader shouldn't support it, because only module authors can handle HMR properly.

**Comment by PepsRyuu** [comment]
Live bindings are impossible to implement for a loader without a compilation step and converting import/export variables to function calls. SystemJS is no exception to this limitation. There is a compilation step required (which is where the real problem lies) to convert these statements into something the module format understands: https://github.com/systemjs/systemjs/blob/master/docs/system-register.md#semantic-cases

Them saying they support live-bindings is a bit of a misleading statement. They have the possibility of helping a compiler support live-bindings by offering a compile target, but they don't offer live-bindings in themselves as that would require compilation (Like how Rollup compiles to SystemJS). I honestly wish JavaScript engines exposed a mechanism to create variable bindings outside of import/export statements, would make it so much easier. :( 

Loaders don't support HMR directly, but they need to be written in such a way that they have the foundation to support HMR. Typically this means ensuring each module remains a separate function scope, having a convention for identifying modules so they can be replaced internally, a mechanism for module invalidation and re-requiring of modules, and following the HMR convention (module/require), and exposing internal implementation details that HMR plugins can attach to (adding ```hot``` to ```module``` for example). My understanding of SystemJS is that it just doesn't provide that type of functionality, and therefore doesn't work well as a compile target for this use case.

I agree and do hope something like ```import.meta.hot``` does become a standardised solution with all of the other big players adopting it. When Webpack/Parcel adopt it, I think that will be the ideal time for Nollup, unless the community around Nollup grows significantly and it becomes a pain-point, but I don't think it's worth bringing in for the time being.

Hope this helps clarify things! :)

**Comment by Amareis** [comment]
>They have the possibility of helping a compiler support live-bindings by offering a compile target, but they don't offer live-bindings in themselves as that would require compilation (Like how Rollup compiles to SystemJS)

Oh, of course there is should be compilation step, but this is really straightforward if you have ES AST (hoist all imported variables, insert export statement after each assignment to exported variable). Honestly, I thinked nollup has compilation currently.

>Typically this means ensuring each module remains a separate function scope, having a convention for identifying modules so they can be replaced internally, a mechanism for module invalidation and re-requiring of modules, and following the HMR convention (module/require), and exposing internal implementation details that HMR plugins can attach to (adding hot to module for example).

All-check! Using system extras you can add import.meta.hot and re-require modules. Also, you can add little extra for possibility to concatenate modules into one bundle and avoid waterfall issue (I done it for my custom toy development bundler).

**Comment by Amareis** [comment]
More to say, with systemjs there is possibility to support `module` API too for backward compatibility - just add line `const module = import.meta.MODULE_API` to top, then compile to system and all done.

**Comment by PepsRyuu** [comment]
Live-bindings compilation is more tricky than it might seem. https://github.com/PepsRyuu/nollup/pull/152/files#diff-5cddd1592605e787b15c73a7eabfa1f0da9fd515f793fb1cacedd14d21fbc194 You have to account for shadowed variables and not export, and then also export when in the syntax you can. It's incredibly messy and fragile stuff. I could be missing something though, so if anyone wants to support this one they're welcome to. It's very much WIP at the moment and I haven't had a chance to dig further into it because of other priorities.

**Comment by Amareis** [comment]
Oh, yep, shadowed variables is really messing (but not too much, I think, since there is only limited cases). About export - there is no need to search place in syntax. `a = someExpr` is replaced to `a = _export('a', someExpr)` and all is good, only comma expressions should be handled carefully (`2, a=3, 4` and `2, a=(3, 4), 5` is different cases). For destructing there is can be similar function helpers, I think.

**Comment by Amareis** [comment]
Honestly, trying to implement live bindings (and, respectively, circular imports), you just reinventing whole systemjs format :) Does it really needed?
