### ISSUE TITLE
Nollup is not recognizing .ts extensions, but will recognize .tsx extensions

### ISSUE THREAD

**Issue by jeremy-coleman** [PepsRyuu/nollup#164]
check this repo, https://github.com/jeremy-coleman/nollup-react-refresh-tsx

In src/@libz/Counter, i'm importing the useInterval hook. If you change the extension .ts , you will get an error saying nollup can't find useInterval.js . Which i think means that it's only checking for .js and .tsx extensions?

**Comment by PepsRyuu** [comment]
As far as I can tell, Nollup and Rollup are behaving identically here. Is there something that Rollup is doing that Nollup is not doing? When you run ```npm run build``` it'll also fail for you (it does for me)?

As a general rule of thumb, Nollup doesn't care about file extensions of files that are being loaded. By default if it doesn't detect any file extension when attempting to load a file, it will default to ".js". It doesn't understand any other extension or know how to resolve them. If there's an issue with ".ts" extensions, it's likely an issue with a plugin.

**Comment by jeremy-coleman** [comment]
ooh yea, it's definitively rollup then. I've always had random issues with rollup. Fixed it by using a typescript plugin, I honestly have no idea why though.

**Comment by PepsRyuu** [comment]
Probably an issue with ```@rollup/plugin-node-resolve```. It has some logic related to TypeScript extension resolution. https://github.com/rollup/plugins/blob/master/packages/node-resolve/src/index.js#L177

If I had to guess, I'm assuming auto-extension detection hasn't been implemented because for each resolveId call, you would have to iterate over all of the possible file extensions, and check if they exist on disk. This could exponentially add significant I/O overhead and significantly reduce performance. If you're planning on mixing extensions, it's probably best to just be explicit in the import statements.
