### ISSUE TITLE
How to get barebones example with HMR working?

### ISSUE THREAD

**Issue by snuup** [PepsRyuu/nollup#165]
Create a barebones example, and changed the start command to

    "nollup -c --hot --environment NODE_ENV:development"

but no hot reloading occurs. What is required?

Thx for your great work.

**Comment by PepsRyuu** [comment]
Are you referring to Hot Module Replacement or Hot Reloading? They're both very different concepts.

If talking about Hot Module Replacement, that's up to the framework plugin to provide. The ```rollup-plugin-hot-css``` that I use in my examples replaces CSS stylesheets, and if you're using frameworks like Preact, you need to use the ```@prefresh/nollup``` plugin which will replace components while preserving state.

If talking about Hot Reloading (full refreshing the page on compilation), unlike other bundlers, that's not done out of the box. You need to implement that manually, you can see an example here: https://github.com/PepsRyuu/nollup/blob/master/docs/hmr.md#hot-reload This is intentional because hot reloading hasn't been as popular since HMR, and ensures devs don't have to fight against default behaviour.

**Comment by snuup** [comment]
Thank you so much, did not give enough attention to that difference.

I currently use rollup + my own microframework and refresh the browser after js (actually ts) changes until now.
For css reloading, i use chrome workspaces, no tooling required.

My preferred module solution would be to use the browsers es6 capabilities and to avoid bundling in the dev phase. Since I love to experiment in the devtools console with my code, making the module elements available requires me to assign them manually to window, that is the drawback here.

If a bundler creates a flat bundle.js (+ ts source maps) without iife or commonjs wrapper that prevents me from accessing the module elements again, then that would be fine as well and be even better than the browser es6 solution.

I hardly use 3rd packages from npm, my bundle size is 100kB raw, non minified, I read my bundle code during dev as well.

Today I evaluate nollup and snowpack to see if I can improve my workflow. Thx for your work and blog Paul, very helpful.
