### ISSUE TITLE
nollup as rollup replacement.

### ISSUE THREAD

**Issue by jackeown** [PepsRyuu/nollup#167]
Hi.
Please help a noob out. :pray: 

I'm familiar with raw **JavaScript/HTML/CSS** because I did a bunch of web programming about 8 years ago using a little bit of **JQuery**. (But mostly just raw JS) I am, however, new to the whole NPM paradigm of packaging everything and using things like **rollup**/**webpack**/**browserify** with tools like **react**/**angular**/etc...It seems to me like there's a bunch of magic everywhere and it's hard to tell what is even happening. (Especially when every tutorial just tells you to use their template without understanding what's going on.)

I like using Flask for my backend. In the past, I've simply used raw JS with flask and jinja templates for everything. This workflow was pretty simple and Flask could watch for changes in my backend and since the JS wasn't compiled, reloads were pretty fast and development was quick. 

I would like to try some new JS stuff (specifically svelte and routify), but would also like to continue using Flask to serve everything. With my default app (I don't understand much of it, but it was from this template: https://github.com/roxiness/routify-starter) I can run `npm run build` which runs `rollup -c` to build my app into `dist/build/bundle.js` I can then allow things from this `dist/build` folder to be served statically by Flask, and everything works great! The problem is that rollup has really slow build times (20 seconds or so.) I saw people online talking about nollup as a way to have faster build times (even the routify example I have uses `npm run dev` to run nollup), but nollup seems to work differently and run its own server to host the app. **I'd like to use nollup to build but still have a `dist/build` folder with the bundle created so that I can serve using Flask.  Is this an option with nollup? Is there a way to do this?**

Although I think Hot Module Replacement is cool, I don't understand how it really works and I'm paranoid about its interaction with backend routes and stuff, so for now I don't really care about this. I just want to be able to refresh the page and get the latest version of the app loaded. 

Thanks,
Jack

**Comment by PepsRyuu** [comment]
Hi @jackeown 

Nollup isn't intended to run in that particular style of setup, nor would I recommend it since you'd lose a lot of benefits and it would make the development architecture fairly complex. You would have to spin up a NodeJS process that uses the Nollup API, write to disk (which isn't recommended because of the amount of writes to the disk in a typical dev flow), and then reference those files from Flask. 

I think the question you need to ask yourself here is, why do you want to serve the bundle from Flask? A typical project setup I use for example, is use Nollup for development, and then compile and serve the app using Nginx for the best static file serving performance. 

If you're concerned about accessing your backend routes from your UI (due to CORS for example), you can always use the built-in proxy in the Nollup config, which will allow you to simulate your app as if it was running on the Flask backend. When you compile for production, you can then just copy the files over to Flask and let Flask take care of serving without the need for a proxy.

**Comment by jackeown** [comment]
> I think the question you need to ask yourself here is, why do you want to serve the bundle from Flask?

I had 2 reasons to serve the bundle using flask.
1. I didn't want to have a different route for the Flask API endpoints during development and production.
2. I want to use the sessions features of Flask.

Now that you mention the Nollup proxy (which I didn't know about), this seems like it could probably suit my needs!
(Are there any reasons why a proxy might not be sufficient?)

Thanks for the info!

**Comment by PepsRyuu** [comment]
A proxy should be fine for that. Proxies are super common, shouldn't be any reason why it wouldn't work. And if for some reason the proxy option isn't sufficient, you can always use ```before```/```after``` hooks in the ```.nolluprc.js``` file and add custom middleware proxy routes to the internal Express instance.

In terms of general software engineering, benefits of proxies:

* Allows you to keep your server code separate from your UI code (microservices design pattern).
* Allows you to keep your backend server private without exposing it to the public internet.
* An alternate to enabling CORS (security risk if improperly used), which helps to prevent CSRF attacks.
* Allows you to map URLs and adjust them if needed.
* Can add additional logic (eg. restrictive gateway, authentication, load balancing etc) without polluting server logic.
* Enables a clean and simple architecture without any tight coupling or integration required.

I use a proxy all of the time for every single project I work on.
