### ISSUE TITLE
Support rollup context/moduleContext config options

### ISSUE THREAD

**Issue by pakomp** [PepsRyuu/nollup#194]
Hi,
I'm using a module that needs top level `this` to resolve to `window` instead of undefined

Would it be possible to add support for rollups config options context or moduleContext?
https://www.rollupjs.org/guide/en/#error-this-is-undefined

**Comment by PepsRyuu** [comment]
It might be possible from the looks of it. I'll have a proper investigation into it later this evening.

**Comment by PepsRyuu** [comment]
Added support for both ```context``` and ```moduleContext``` in ```0.16.2```. Let me know if it solves your use case! :)

**Comment by pakomp** [comment]
Hi, looks like our nollup problem wasnt with `this` being undefined, that only happened in rollup. 

In nollup the problem instead seems to be a parent class (PdfPageBase) not being included in the resulting code in 
`nollup-int:///node_modules/@syncfusion/ej2-pdf-export/src/implementation/pages/pdf-page.js` 
while the imports a there when looking at the 
`node_modules/@syncfusion/ej2-pdf-export/src/implementation/pages/pdf-page.js` source, 
so maybe it has something to do with some kind of tree shaking? Not sure if nollup does that or not.

**Comment by PepsRyuu** [comment]
Nollup doesn't do tree-shaking, so code shouldn't be omitted. Off the top of my head not entirely sure what the problem would be. Do you have a reproducible example?

**Comment by pakomp** [comment]
Here is a basic example
[Example](https://github.com/pakomp/syncfusion-test)

**Comment by PepsRyuu** [comment]
Not entirely sure what's happening still, but it looks like it's some sort of deeply nested circular dependency problem. This is going to take quite some time to figure out how to fix. It's fairly hard to track this given how massive the package is. I'll have to try and replicate this in some test cases and work from there.

As a workaround, configure ```node-resolve``` in your Rollup config to point to the compiled packages provided by ```@syncfusion```. This should be done anyways, because it will improve your build times. The ```@syncfusion``` packages in their ```package.json``` files are pointing ```module``` property to the ```src``` directory (which isn't ideal or optimal), and instead have a separate custom property ```es2015``` defined pointing to the compiled ESM module. If you use the below configuration, it will work no problem:

```
node_resolve({
    mainFields: ['es2015', 'module', 'main']
})
```

Even if the circular dependency issue is fixed, I'd strongly advise keeping that configuration because it will work best with those packages. But I'll be trying to figure this out in the meantime because it will likely affect other packages out there.

**Comment by pakomp** [comment]
Thanks that fix seems to work fine.
