### ISSUE TITLE
Statically imported module will still be imported dynamically

### ISSUE THREAD

**Issue by charlag** [PepsRyuu/nollup#204]
Hi
Scenario: in the same chunk you import file both statically and dynamically.
Expected: after doing static import dynamic one would return already imported module instance.
Actual: dynamic import is still executed and after that the check is done whether the module is already instantiated.

I've made a tiny example to demonstrate:

https://github.com/tutao/nollup-bug/tree/dynamic-import

Why is this a problem:
In many places dynamic ES6 import is not supported. E.g. it works in worker only in Chrome and in Safari 15+ on iOS. For us iOS app does not currently work with nollup because some common worker/client code imports things dynamically which should not be a problem as we already import them statically before that. We can refactor it but it's still odd behavior to import things twice.

**Comment by PepsRyuu** [comment]
I'm confused by the expectation here. If ```import()``` is not supported, in an unsupported browser, it should just crash because of unrecognised syntax, right? Even if the dynamic import is skipped on the basis the module is already loaded, the presence of the syntax would still make it fail?

**Comment by charlag** [comment]
Hey
That thing about dynamic import failing is just describing our use case. It will be parsed but won't be implemented in Worker in Firefox or older Safari versions.

Regardless of that I think it's odd that the same module will be imported again? It probably has no side effects (I'm not sure) but doesn't seem right.

**Comment by PepsRyuu** [comment]
The same module will be outputted twice, but as far as I can tell it should be only instantiated once. Since the module will have the exact same identifier, it will see that it's already instantiated so it will just return that instead to the import callback, so there shouldn't be any side effects. Is it actually running the module twice? The only reason it's not removed from the dynamic chunk is because it didn't seem necessary to spend processing time cleaning it up, and no other optimisations are done either.

**Comment by charlag** [comment]
I am struggling to make myself clear.
Module is emitted twice. This is as expected.
Module is not instantiated twice. This is as expected.
import() is still executed. This is not as expected.

When `localRequire.dynamic()` is executed it is checked whether the chunk is already imported or not. As we are talking about inlined module it doesn't affect it. It calls `import()` on it still and then *later* checks whether module is instantiated. As it already is it stops.

The issue I'm describing is that this `import()` is not necessary to execute when the module is already instantiated. This likely slows down loading quite a bit as well as introduces strange side effects (like in our case where we don't expect `import()` to be executed).

I hope I could make it more clear.

**Comment by PepsRyuu** [comment]
Thanks for the clarification. I'll need to have a look at what native ```import()``` does as well. 

I'm not entirely sure if I agree with that behaviour. The goal here is to mimic Rollup as much as possible, as opposed to mimicing ESM, so that way both tools can be interchanged without behaviour change. I haven't looked into it yet, but I assume Rollup would also preserve the ```import()``` call and run the imported chunk. Will need to look into this further to make sure behaviour is aligned.

**Comment by PepsRyuu** [comment]
Released ```0.17.0``` which includes an optimisation where if the module is statically imported, it won't run the import. 🙂

**Comment by charlag** [comment]
Thank you a lot! 💚
