### ISSUE TITLE
React fast refresh integration

### ISSUE THREAD

**Issue by CodeWitchBella** [PepsRyuu/nollup#34]
React has new official way to do HMR called [fast refresh](https://github.com/facebook/react/issues/16604)

Integration with bundler involves few steps (outlined in [this comment](https://github.com/facebook/react/issues/16604#issuecomment-528663101))

1. injecting code into modules to perform hot reload (this is easy using transform hook)
2. adding babel plugin (again easy)
3. wrapping module load function with some code (this is currently impossible, I think)

## My implementation

https://github.com/CodeWitchBella/nollup/commit/f8737956e9157ef7d7e0fc84eddfa368f0907dd9

This does do everything that is needed (I think) in rollup plugin except point 3 which is implemented using new hook.

## Proposed change

Add new hook `nollupModuleWrap` which can add code around `module.__impl` call in `lib/index.js` (see commit linked above for implementation)

**Comment by PepsRyuu** [comment]
Wow! Thanks for looking into this, I wasn't aware of React Refresh at all. 

Going to need to do a bit of reading to fully understand the context. Has there been any implementation from Parcel or Webpack yet for this?

**Comment by CodeWitchBella** [comment]
There are a few (also incomplete) implementations linked in the issue on the react repo (linked above).

**Comment by PepsRyuu** [comment]
https://github.com/PepsRyuu/nollup/commit/e065a3ca9a1a127d841863a72614830299e7075c

Here's my initial attempt at it. Made a few modifications:

* Support for both functional and class components.
* Instead of ```require/import```, using ```nollupBundleInit``` hook.
* Simplified transform step, shouldn't require a sourcemap in theory.

Thoughts? 🙂

**Comment by CodeWitchBella** [comment]
Awesome :slightly_smiling_face:

That approach is certainly simpler but I think it depends too much react-refresh internals. But maybe that is ok and we can fix it if it breaks...

As for sourcemaps - my transform also did not need sourcemaps, because I only append. That's why i returned `map: null` which means preserve source maps ([relevant rollup documentation](https://rollupjs.org/guide/en/#transformers)) I don't know what is the behavior for returning just string? Is it the same?
Your transformation breaks (I think) source maps for first line of code.

But most importantly I see that you used same approach for injecting code for each module load - if we agree that is the best way to do this maybe we can release that to npm? Then we can iterate on plugin which can be installed separately (and I can use it in my projects without `npm link`ing)

One last note: your transform runs into risk of conflict if transformed code contains `checkRefresh` and while my transform has same risk it is much less likely that it will contain `__FreshUtils__`

**Comment by PepsRyuu** [comment]
Yeah I was a bit hesistant to use the approach of ```fs.readFileSync```, but I like it because it means that the code can be kept synchronous without the need for an additional chunk. The ```process.env``` replacement should always be fine regardless of changes, but the ```module.exports = ``` is indeed a problem. Also it depends on the fact that it's a pure module (no external calls with ```require``` for example). Not sure about the alternative approaches. I fully see why you used ```import()``` but the asynchronous chunk feels like it could be an issue for order sensitive code, etc.  

Hmmm, actually yeah I think the transform can be an issue for modules that don't import anything. If you have a module that just has exports, it could break the very first line. Was trying to keep the imports structured but I think it's best to stick it at the bottom of the file like you did. :D 

Not entirely sure how I feel about ```nollupModuleWrap``` yet. I think I need to properly formalise all three of the nollup hooks and make them more intuitive to use. I do feel something like it is absolutely needed to reduce bundle size though. The bloat without it would be far too heavy. Going to experiment with these hooks a bit more and see what I can do in terms of API design. 

Good catch on ```checkRefresh```. Something like ```__$RefreshCheck$__``` might be more suitable.

**Comment by PepsRyuu** [comment]
Just a small update that I haven't forgotten about this. Been too pre-occupied by other stuff lately. Just writing some test cases and should have a release soon! :)

**Comment by PepsRyuu** [comment]
Released ```nollupModuleWrap``` in ```0.7.5``` with example project.

If there's a full plugin released, let me know and I'll update the example!

**Comment by PepsRyuu** [comment]
Example updated to use this new plugin: https://github.com/PepsRyuu/rollup-plugin-react-refresh
