### ISSUE TITLE
exclude subfolder from nollup watch

### ISSUE THREAD

**Issue by markope** [PepsRyuu/nollup#69]
I keep my build target folder as a subfolder of the main project. I start nollup from the main project folder, so nollup watches the build target as well which results in constant recompile.

In rollup there is a config 
```
watch: {
    exclude: 'dist'
}
```

This seems a basic requirement to me. Am I missing something maybe?

**Comment by PepsRyuu** [comment]
Hi @markope 

I could be wrong, but as far as I understand, the implementation currently should be matching Rollup's own watch functionality.

In general, files in an output directory shouldn't be modified anyways. Can you share a copy of the ```rollup.config.js``` file so I can get a better idea of why this would be causing issues?

**Comment by markope** [comment]
thanks for the quick response. Here is my `rollup.config.js`. 

```javascript
import copy from 'rollup-plugin-copy'
import resolve from 'rollup-plugin-node-resolve'
import babel from 'rollup-plugin-babel'
import clear from 'rollup-plugin-clear'
import { terser } from 'rollup-plugin-terser'
import commonjs from 'rollup-plugin-commonjs-alternate' // use this if you use nollup instead of rollup
import static_files from 'rollup-plugin-static-files'

let config = {

    onwarn: function(warning, warn) {
        if (warning.code === 'CIRCULAR_DEPENDENCY') return
        warn(warning)
    },

    input: ['src/index.js'],

    output: {
        dir: './build/es6-bundled',
        name: 'reswarm_bundle',
        compact: true,
        format: 'esm',
        dynamicImportFunction: '__import__',
    },

    watch: {
        exclude: './build'
    },

    plugins: [
        clear({
            targets: ['./build/es6-bundled'],
            // optional, whether clear the directores when rollup recompile on --watch mode.
            watch: true
        }),        
        babel(),
        resolve({
            only: [/^(?!locale-).*$/]
        }),
        commonjs({
            exclude: [ 'node_modules/autobahn-browser/**' ],
        }),
        terser(),
        static_files({
            include: ['./public']
        }),
        copy({
            targets: [
                { src: 'src/modules/language', dest: 'build/es6-bundled/src/modules' },
                { src: 'node_modules/d3/dist/d3.min.js', dest: 'build/es6-bundled/node_modules/d3/dist/d3.min.js' },
                { src: 'node_modules/@webcomponents/webcomponentsjs', dest: 'build/es6-bundled/node_modules/@webcomponents' }
            ],
            hook: 'writeBundle'
        })
    ]
}

export default config
```

and here is my `.nolluprc.js`: 

```javascript
module.exports = {
    hot: false,
    port: 8083,
    contentBase: './public',
    historyApiFallback: true,
    proxy: {
        '/download': 'http://localhost:8084',
        '/locale-reswarm': 'http://localhost:8084',
        '/locale-reswarm-en': 'http://localhost:8084'
    }
}
```

**Comment by PepsRyuu** [comment]
Plugins such as ```clear```, ```terser```, ```static_files```, ```copy``` should ideally be used when you're generating a production build. Not only will this help to reduce issues with watching, but it will also speed up performance because those type of plugins are usually not needed in development. Uglifying code for example can be time-consuming and makes it more difficult to debug code. Similarly, writing content to disk can create an I/O bottle-neck. 

I recommend having a closer look at the examples like this one here, which only adds plugins if ```process.env.NODE_ENV``` is set to ```production```: https://github.com/PepsRyuu/nollup/blob/master/examples/example-react-refresh/rollup.config.js

My biggest concern with your config is the ```copy``` for the external third-party libraries. I assume that they're being loaded with script tags and hence needing to be copied out of ```node_modules``` so that they can be referenced by the ```index.html``` file. As mentioned earlier, disk writing should be avoided in development because of performance and watch conflicts. If for some reason ```import``` can't be used because they're fairly hefty in size, you could use an Express route instead t expose your node_modules:

**.nolluprc.js**
```
let express = require('express');

module.exports = {
    before: app => {
        // This is just off the top of my head, so likely incorrect for your setup
        // but you can get the general idea of what this will do:
        app.use('/node_modules', express.static('./node_modules'));
    }
}
```

Hope this helps!

**Comment by markope** [comment]
My original problem was solved by removing the `static_files` plugin from rollup.  Thanks for your help!

I'l also implement all the other changes you suggested.
