### ISSUE TITLE
React hot loading without Babel

### ISSUE THREAD

**Issue by ashubham** [PepsRyuu/nollup#73]
We currently use Typescript/Rollup to generate and bundle our code. The typescript target ES is ES2018.

We do not use `Babel` anywhere in the build pipeline, since typescript is enough. Is it possible to use react-hot-loading with `nollup` without introducing Babel ?

If it absolutely needs to be, what is the minimal footprint it can have with no effect on build times.

Also, it will be great if we could post an example with Typescript and hot-loading.

**Comment by PepsRyuu** [comment]
Hi @ashubham 

React Hot Loader uses a Babel plugin to inject wrapper code in each component file. As far as I know, and someone can correct me if I'm wrong, but it's pretty much essential for Hot Module Replacement to work. This is also the case for the newer React Refresh, it also requires Babel to be used. You have three options as far as I can tell:

* Configure your setup so that TypeScript does type annotations only, and then Babel to do the rest.
* Configure your setup so TypeScript does everything, but then Babel only does the HMR stuff.
* Go all in on Babel using a TypeScript preset using the IDE to validate types instead.

I don't use TypeScript so I honestly don't know what the best would be in terms of performance, but for the most part, Babel is pretty much essential. React Hot Loader and React Refresh are very restrictive in terms of where they work.

**Comment by ashubham** [comment]
Thanks for the info!
