### ISSUE TITLE
Why faster than rollup dev mode?

### ISSUE THREAD

**Issue by xcodebuild** [PepsRyuu/nollup#75]
Hi PrpsRyuu,

This stuff looks quite cool. But I'm a little confused, `rollup` doesn't do many optimisations in dev mode, too. Why is `nollup` faster than `rollup` dev mode?

**Comment by PepsRyuu** [comment]
Hi @xcodebuild, thanks for the question!

You're correct in that Rollup can be "de-optimised" in order to improve the dev experience, but there's still some core differences that help to improve performance. 

If you inspect Nollup's bundles, they're effectively just string concatenations with function scopes wrapped around each module. This is very similar to how Webpack behaves in development, because it's fast. Rollup on the other hand still does scope hoisting even with optimisations disabled, which is much slower. 

There's also a bunch of other shortcuts taken to help improve performance. Caching for example is a core feature in Nollup and tied deeply into the implementation which allows for really quick rebuilds. This along with how Nollup bundles modules into function scopes enables cool stuff like Hot Module Replacement to further enhance the developer experience. 

Finally, Nollup doesn't bother checking for all of the additional bundling config options that Rollup provides because a lot of the options don't make sense in development at all, which also helps to speed up performance.

Hope this helps clarify things! :)

**Comment by xcodebuild** [comment]
Thanks for your clear response 👍
