### ISSUE TITLE
Use server-sent events instead of WebSocket

### ISSUE THREAD

**Issue by rixo** [PepsRyuu/nollup#90]
[SSE](https://developer.mozilla.org/en-US/docs/Web/API/Server-sent_events/Using_server-sent_events) uses normal HTTP and so:

- it would be easier to integrate the Nollup middleware into a custom dev server / express app

- it would be easier to proxy to Nollup's dev server (because proxying WS is complicated)

- as a bonus I'm found of, browsers have an auto retry on SEE, so you can have a cheap "browser automatically picks server back up, after a server restart"

**Comment by PepsRyuu** [comment]
I've used SSE before when developing a large scale notification system for a massive large scale system, and while I do like some of those benefits for SSE, I'd be very reluctant to use it again.

One of the big downsides is that it hogs a HTTP connection per tab. Browsers are limited in the number of HTTP requests they can make simultaneously to a single domain across all tabs (typically 6). This is normally solved by using a Shared Worker that manages a single SSE connection for all tabs, but it requires quite a bit of code and gets complex quickly.

And then some browsers like Firefox don't support EventSource in SharedWorker last I checked, so a polyfill will be required and those polyfills tend to be very unreliable. Had to write my own one at one point to solve the problem. 

Another problem is that support in general across the board with server side frameworks isn't great either, since Web Workers are far more popular. I remember actually having proxy issues with SSE because long polling HTTP wasn't expected, but because WebSockets are more popular, while still complex, was easier.

Not saying yes or no to the idea, but I just don't know if it's really worth it considering the complexity that's involved in making it reliable.

**Comment by rixo** [comment]
Very interesting feedback. I didn't know. Might be of some use one day, in real life.

But I don't think these drawbacks are really too limiting for a dev server. I don't think we need to make it _that_ reliable. We tend to use cutting edge browsers, and they're generally pumping their data from a server right on the same machine...

I have used HMR over SSE for some time with my own plugin, and it's been a pleasant experience overall (I must say I love the automatic resume on server restart). No notable hurdles.

When I wrote my plugin's dev server, I took massive inspiration from your own, and so it was also using WS initially. I changed this once, in a hurry, because a pal wanted to HMRize a thing he had in CodeSandbox and CodeSandbox wasn't playing too well with WS. It took like 30 min to adapt the server and HMR client to SSE into something working. They have very close functionalities and APIs (as long as you don't send messages from the client, ofc).

Also, the proxy / middleware benefit I'm mentioning is not theoretical. To adapt into complex projects like Sapper that have their own non-dumb server, proxy or middleware (instead of cli) is required. And for that, especially with proxying, WS are a hurdle.

Since it's relatively easy to abstract a common API and they offer a different set of benefits, I think it would make sense to have them both.

**Comment by PepsRyuu** [comment]
If I had to, I would potentially consider it as a flag: ```--sse```

That reminds me, I remember when working with SSE before, there was proxying issues because HTTP likes to buffer, sending data to the client in chunks. In either case, it sounds like there's always going to be some form of hurdle.

I think the pros and cons can be debated forever. The consensus across Webpack, Parcel, Vite, Snowpack all seem to be for WebSocket at the moment, I would also throw my hat there as well based on negative experiences with SSE. 

Would require a fair bit of abstraction for this to be implemented even in a basic form (would have to have helpers to convert JSON into the correct ```data:``` payload). Is this an immediate blocker at the moment?

**Comment by rixo** [comment]
> Is this an immediate blocker at the moment?

Nope, just an idea. Since I was launched in a feedback session...

The easier proxying would be a nice to have, but it's not insurmountable. And I think the current projects with this need will all go the middleware route anyway, where this is even less of an issue.

The automatic revive can also be implemented quite easily with a WS client. That's actually the part I'm missing the most, even if it probably seems trivial... I might have a look at it myself when things settle a bit, if you're interested.

**Comment by PepsRyuu** [comment]
Automatic revival I'm not sure would even work correctly. Because theoretically, the server would be completely out of sync with the previous bundle code. Module ids won't match most likely so HMR updates will fail to replace the modules.

**Comment by rixo** [comment]
Yeah sorry, by automatic revival I meant full reload when the server's back online.

Indeed HMR revival would be prohibitively complicated as compared to the tiny gain. It is even completely impossible in many cases.

But a little poller launched after disconnect can save a lot of <kbd>Alt</kbd> <kbd>Tab</kbd> <kbd>F5</kbd> <kbd>Alt</kbd> <kbd>Tab</kbd>. A whole lot!

**Comment by PepsRyuu** [comment]
Closing, as I'm fairly confident WebSocket is still the way to go on this one, not seeing much of a reason to go for SSE still, and my experience with SSE wasn't great.
